<?php

return array(
    '病人管理'  => array(
        '病人列表' => array('hidden'=>false,
                            'url' => '/Master/Index/index',
                        ),
        '添加病人' =>array('hidden'=>false,
                            'url' => '/Master/Patient/index',
                        ), 
        '病人信息' =>array('hidden'=>true,
                            'url' => '/Master/Patient/info',
                        ), 
    ),
    '统计管理' => array(
        '按月统计' =>array('hidden'=>false,
                            'url' => '/Master/Spending/totalMonth',
                        ),  
        '按日统计' =>array('hidden'=>false,
                            'url' => '/Master/Spending/totalDay',
                        ),  
        '按年统计' =>array('hidden'=>false,
                            'url' => '/Master/Spending/totalYear',
                        ), 
    ),
    '消费表管理' => array(
        '生成下月消费'=>array('hidden'=>false,
                            'url' =>  '/Master/Spending/addNext',
                        ),
        '生成当月消费'=>array('hidden'=>false,
                            'url' => '/Master/Spending/addCurrent',
                        ), 
    ),
    '医院管理'=>array(
        '医院列表' =>array('hidden'=>false,
                            'url' => '/Master/Hospital/index',
                        ),  
        '添加医院' =>array('hidden'=>false,
                            'url' => '/Master/Hospital/add',
                        ),  
        '添加医生'=>array('hidden'=>false,
                            'url' => '/Master/Doctor/index',
                        ), 
        '医院信息'=>array('hidden'=>true,
                            'url' => '/Master/Hospital/info',
                        ), 
        '添加病种'=>array('hidden'=>false,
                            'url' => '/Master/Hospital/illness',
                        ), 
    ),   
    '管理员'=>array(
        '管理员列表' =>array('hidden'=>false,
                            'url' =>  '/Master/Admin/index',
                        ), 
        '添加管理员' =>array('hidden'=>false,
                            'url' =>  '/Master/Admin/addAdmin',
                        ), 
        '账户信息修改' =>array('hidden'=>false,
                            'url' =>  '/Master/Admin/update',
                        ), 
        ),
);